rules:
  - name: check_if_contains_allowed_map_settings
    module: rules.setting
    class_name: Valid
    description: "Check if the map has allowed map settings"
    type: require
    params:
      field: "sv_kog_map_quests"
      type: list
      values:
        - Q_NO_HAMMER
        - Q_NO_PLATFORM
        - Q_TEAM_15
    depends_on: []
