name: 'KoG Map Workflow'
description: 'The official KoG maps workflow'

inputs:
  map:
    description: 'The map to be tested'
    required: true
    default: "Aip-Gores"

outputs:
  status:
    description: 'Returns a json object with the status'
    value: ${{ steps.map-workflow-output.outputs.status }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: "Set up Python"
      uses: actions/setup-python@v5

    - name: Cache the virtualenv
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/uv.lock') }}

    - name: Install the project
      shell: bash
      run: uv sync --all-extras --dev
      working-directory: ${{ github.action_path }}

    - name: Get the result
      id: map-workflow-output
      run: |
            uv pip install .
            for file in $(find . -type f -name "*.map"); do
              uv run maps_workflow/main.py --map $file
            done
      shell: bash
      working-directory: ${{ github.action_path }}
