name: 'KoG Map Workflow'
description: 'The official KoG maps workflow'
inputs:
  map:
    description: 'The map to be tested'
    required: true
    default: "Aip-Gores"
outputs:
  status:
    description: 'Returns a json object with the status'
    value: ${{ steps.map-workflow-output.outputs.status }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install poetry
      run: python -m pip install poetry==1.8.4

    - name: Cache the virtualenv
      uses: actions/cache@v2
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      run: python -m poetry install

    - name: Pass Inputs to Shell
      run: |
              echo "INPUT_MAP=${{ inputs.map }}" >> $GITHUB_ENV
      shell: bash

    - name: Get the result
      id: map-workflow-output
      run: python -m poetry run ci
      shell: bash
