name: 'KoG Map Workflow'
description: 'The official KoG maps workflow'

inputs:
  maps:
    description: 'The maps to be tested'
    required: true
    default: "Aip-Gores.map"
  GITHUB_TOKEN:
    type: string
    description: Github token passed from calling workflow
    required: true
  GITHUB_REPOSITORY:
    type: string
    description: Github repository from the from calling workflow
    required: true

outputs:
  status:
    description: 'Returns a json object with the status'
    value: ${{ steps.map-workflow-output.outputs.status }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Cache the virtualenv
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/uv.lock') }}

    - name: Install the project
      shell: bash
      run: |
        uv sync --all-extras --dev
      working-directory: ${{ github.action_path }}

    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.GITHUB_REPOSITORY }}
        token: ${{ inputs.GITHUB_TOKEN }}

    - name: Get the result
      id: map-workflow-output
      run: |
            tree .
            IFS=',' read -ra FILES <<< "${{ inputs.maps }}"
            for file in "${FILES[@]}"; do
              if [[ $file == *.map ]]; then
                uv run maps_workflow/main.py --map ${{ github.workspace }}/$file
              fi
            done
      shell: bash
      working-directory: ${{ github.action_path }}
